CREATE TABLE IF NOT EXISTS "Credit" (
  "id" TEXT PRIMARY KEY,
  "projectName" TEXT NOT NULL,
  "vintage" INTEGER NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "ownerCompany" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "SignerSecret" (
  "id" TEXT PRIMARY KEY,
  "ciphertext" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "authTag" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "TransferCache" (
  "id" TEXT PRIMARY KEY,
  "onChainId" BIGINT NOT NULL UNIQUE,
  "direction" TEXT NOT NULL,
  "counterparty" TEXT NOT NULL,
  "amount" DOUBLE PRECISION NOT NULL,
  "status" TEXT NOT NULL,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
